# Generated by Django 3.1.7 on 2021-04-09 19:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='picture',
            field=models.FileField(default='images/no_image.png', upload_to='images'),
        ),
    ]
