# Generated by Django 3.1.7 on 2021-04-09 20:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0002_user_picture'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='picture',
            field=models.ImageField(default='network/default.png', upload_to='network/'),
        ),
    ]
