# Generated by Django 3.1.7 on 2021-04-10 08:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0003_auto_20210409_2220'),
    ]

    operations = [
        migrations.RenameField(
            model_name='follower',
            old_name='user',
            new_name='follower',
        ),
        migrations.RemoveField(
            model_name='follower',
            name='post',
        ),
        migrations.AddField(
            model_name='follower',
            name='following',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='following', to='network.user'),
            preserve_default=False,
        ),
    ]
